language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="cmake libpantheon-files-core-dev elementary-icon-theme libcanberra-dev libdbus-glib-1-dev libgail-3-dev libgee-0.8-dev libglib2.0-dev libgranite-dev libgtk-3-dev libnotify-dev libpango1.0-dev libplank-dev libsqlite3-dev libunity-dev libzeitgeist-2.0-dev valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && mkdir build && cd build && cmake .. && env CTEST_OUTPUT_ON_FAILURE=true make all"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && mkdir build && cd build && cmake .. && env CTEST_OUTPUT_ON_FAILURE=true make all"

script:
 - echo BUILDS PASSED
